import { createContext, useContext, useState, ReactNode } from "react";

export type Lang = "en" | "ru" | "uz";

export const translations = {
  en: {
    // NAV
    navHome: "Home", navAbout: "About", navCommittees: "Projects", navTeam: "Team",
    navSchedule: "Events", navRegister: "Join Us", navSponsors: "Sponsors", navContact: "Contact",
    // HOMEPAGE
    dateTag: "Ecological Project",
    heroLine1: "Yashil", heroLine2: "Qo'llar", heroLine3: "let's unite", heroLine4: "for", heroLine5: "nature.",
    heroSub: "A project to raise ecological awareness and culture among young people and protect the environment — promoting the wise use of resources, reducing waste, and strengthening ecological responsibility.",
    heroCta2: "Join us on this journey.",
    heroBadge: "· Join the movement",
    btnRegister: "Join Us", btnCommittees: "See What We Do",
    stat0val: "1,000+", stat0lbl: "Volunteers", stat1val: "25+", stat1lbl: "Events",
    stat2val: "14", stat2lbl: "Regions", stat3val: "6", stat3lbl: "Activity types",
    councilsLabel: "What We Do", councilsTitle: "Types of Activities", viewAll: "See All Activities",
    ctaTitle1: "Building a Clean &", ctaTitle2: "Sustainable Future",
    ctaSub: "Our goal is to grow ecological culture among young people. Join 1,000+ active volunteers already part of the movement.",
    btnContact: "Contact Us",
    homeCommittees: [
      { code: "01", name: "Ecological Actions", topic: "Cleaning up areas, sorting waste, and planting trees and saplings, with competitions to boost ecological responsibility." },
      { code: "02", name: "Plogging Events", topic: "Collecting litter while running or walking, turning fitness into ecological activity." },
      { code: "03", name: "Digital Eco-Promotion", topic: "Ecological challenges, trends, videos, and posters shared with the wider public on social media." },
      { code: "04", name: "Waste Reduction & Recycling", topic: "Interactive sessions where young people learn to sort and recycle waste." },
      { code: "05", name: "Ecological Safety Training", topic: "Practical skills in ecological safety and the wise use of natural resources." },
      { code: "06", name: "Eco-Club Network", topic: "Yashil Qo'llar eco-clubs in schools and universities, with inter-club competitions and challenges." },
    ],
    // ABOUT
    aboutTag: "About Us",
    aboutHero: "Restoring Uzbekistan, One",
    aboutHeroEm: "Region at a Time",
    aboutConferenceTag: "The Organization",
    aboutWhatTitle: "What is Yashil Qo'llar?",
    aboutP1: "Yashil Qo'llar is a community organization where volunteers take part in real reforestation projects — researching local ecosystems, planting trees, and restoring green belts across Uzbekistan.",
    aboutP2: "Volunteering with us builds practical, lasting skills: teamwork, land stewardship, project planning, community organizing, and environmental literacy.",
    aboutP3: "Yashil Qo'llar brings a proven, transparent model of community-led restoration to every region of Uzbekistan.",
    aboutSteps: [
      { step: "01", title: "Region Assignment", desc: "Each volunteer joins a project team in one of Uzbekistan's 14 regions." },
      { step: "02", title: "Site Assessment", desc: "Volunteers study the local soil, climate, and community needs before planting." },
      { step: "03", title: "Planting & Restoration", desc: "Teams plant trees, build green belts, and maintain young saplings together." },
      { step: "04", title: "Impact Reporting", desc: "Every tree is GPS-tagged and survival data is published openly." },
    ],
    aboutHomeTag: "Where We Started",
    aboutHomeTitle: "Tashkent, Uzbekistan",
    aboutHomeP1: "Founded in 2025, Yashil Qo'llar began with a small volunteer clean-up in Tashkent.",
    aboutHomeP2: "Today the organization coordinates ecological projects across all 14 regions of the country.",
    aboutValuesTag: "Our Philosophy", aboutValuesTitle: "What We Stand For",
    aboutValues: [
      { icon: "🌱", title: "Root Causes First", desc: "Every project begins with soil analysis, community consent, and a long-term maintenance plan." },
      { icon: "🤝", title: "Community-Led", desc: "Local families, schools, and farmers design and own each project. We are the facilitators." },
      { icon: "📍", title: "Place-Specific", desc: "Each region gets species, layouts, and water strategies matched to its own climate." },
      { icon: "📊", title: "Radical Transparency", desc: "Every tree is GPS-tagged. Every result — including failures — is public." },
    ],
    aboutTimelineTag: "Our Journey", aboutTimelineTitle: "History of Yashil Qo'llar",
    aboutTimeline: [
      { year: "2025", event: "Yashil Qo'llar Founded", desc: "The first clean-up and planting drive took place in Tashkent." },
      { year: "2025", event: "Going Regional", desc: "Volunteer teams formed in Farg'ona, Samarqand, and Navoiy." },
      { year: "2025", event: "GPS Tracking Launched", desc: "Every tree planted began being tagged and tracked publicly." },
      { year: "2025", event: "1,000+ Volunteers", desc: "The volunteer network passed one thousand active members." },
      { year: "2026", event: "All 14 Regions", desc: "Yashil Qo'llar became active in every region of Uzbekistan." },
      { year: "2026", event: "25+ Projects", desc: "Our most ambitious year yet — 25+ active ecological projects." },
    ],
    aboutCtaTitle: "Be Part of the Story",
    aboutCtaSub: "Join volunteers across Uzbekistan restoring forests and green belts, region by region.",
    aboutCtaBtn: "Join Yashil Qo'llar",
    // PROJECTS (formerly "committees")
    committeesTitle: "Projects",
    committeeLess: "▲ Less", committeeMore: "▼ More",
    committeeSeats: "spots",
    committees: [
      { code: "TSH", name: "Tashkent Green Belt", level: "Beginner", size: "40", topic: "Urban tree planting and green-belt restoration in the capital.", topic2: "Community nurseries in residential districts", chair: "Malika Yusupova", desc: "Volunteers plant and maintain trees along Tashkent's green belt, working closely with local schools and residents.", color: "from-blue-600 to-cyan-500" },
      { code: "FAR", name: "Farg'ona Orchards", level: "Intermediate", size: "35", topic: "Community orchards and sapling nurseries across the valley.", topic2: "Water-efficient irrigation for young saplings", chair: "Jasur Toshmatov", desc: "This project builds community orchards and trains local farmers in sustainable sapling care.", color: "from-green-700 to-emerald-500" },
      { code: "QQR", name: "Qoraqalpog'iston Restoration", level: "Advanced", size: "30", topic: "Combating desertification near the Aral Sea region.", topic2: "Salt-tolerant species trials for reclaimed land", chair: "Nilufar Ergasheva", desc: "One of our most challenging projects — restoring vegetation on land affected by the Aral Sea's retreat.", color: "from-purple-700 to-violet-500" },
      { code: "NAV", name: "Navoiy Reforestation", level: "Intermediate", size: "20", topic: "Large-scale reforestation on reclaimed arid land.", topic2: "Training the next generation of local volunteers", chair: "Aziz Karimov", desc: "A large-scale planting effort across Navoiy's arid terrain, combining reforestation with volunteer training.", color: "from-amber-700 to-yellow-500" },
    ],
    // JOIN / VOLUNTEER SIGN-UP (formerly "registration")
    regTag: "Join Our Work", regTitle: "Volunteer Sign-Up",
    regSuccessTitle: "Application Received!",
    regSuccessSub: "Thank you for applying. Our team will review your application and contact you via email.",
    regSuccessBtn: "Submit another application",
    regFeesTitle: "How to Get Involved",
    fees: [
      { type: "Volunteer", deadline: "Open year-round", price: "Free", desc: "Join a regional project, planting kit and training included", badge: "Most Popular", badgeColor: "bg-green-500/10 text-green-400 border-green-500/20" },
      { type: "Team Lead", deadline: "By application", price: "Free", desc: "Coordinate a local project team and report progress", badge: "", badgeColor: "" },
      { type: "Partner Org", deadline: "By application", price: "Free", desc: "Bring your school, company, or community group", badge: "Group", badgeColor: "bg-blue-500/10 text-blue-400 border-blue-500/20" },
    ],
    regDeadline: "Availability:",
    regFields: { firstName: "First Name", lastName: "Last Name", email: "Email Address", committee1: "1st Region Preference", committee2: "2nd Region Preference", experience: "Volunteering Experience", motivation: "Motivation Statement", motivationPlaceholder: "Why do you want to volunteer with us?", selectCommittee: "Select a region", selectExperience: "Select experience level", expNone: "No prior volunteering experience", exp12: "1–2 projects", exp35: "3–5 projects", exp5: "5+ projects", submit: "Submit Application" },
    // CONTACT
    contactTitle: "Contact Us",
    contactLocation: "Location",
    contactAddress: "Tashkent, Uzbekistan",
    faqTag: "Quick Answers", faqTitle: "Frequently Asked Questions",
    faq: [
      { q: "Who can volunteer with Yashil Qo'llar?", a: "Anyone in Uzbekistan can join — students, professionals, and families. No prior experience is required for most projects." },
      { q: "Is there a cost to volunteer?", a: "No — volunteering is free. Planting kits and training are provided for every project." },
      { q: "Which region will I be assigned to?", a: "You choose your preferred region when you sign up, and our team confirms your assignment by email." },
      { q: "When will I hear back after applying?", a: "Applications are usually reviewed within 1–2 weeks." },
      { q: "Can my school or company volunteer as a group?", a: "Yes! We welcome school and company groups — contact us to arrange a group project." },
    ],
    // SCHEDULE (formerly conference schedule → now event calendar)
    scheduleTag: "Upcoming Events", scheduleTitle: "Volunteer Calendar",
    scheduleCtaTitle: "Ready to Join Us?",
    scheduleCtaSub: "Find your region's next planting day and be part of it.",
    scheduleCtaBtn: "Join Yashil Qo'llar",
    scheduleTypeLabels: { opening: "Kickoff", committee: "Planting Day", social: "Community", break: "Break", closing: "Wrap-up" },
    scheduleDays: [
      {
        day: "Day 1", date: "To be announced", events: [
          { time: "09:00 – 10:00", title: "Orientation", subtitle: "Welcome and safety briefing for new volunteers", type: "opening", location: "Regional Hub" },
          { time: "10:00 – 13:00", title: "Planting Session I", subtitle: "Tree planting and green-belt work", type: "committee", location: "Project Site" },
          { time: "13:00 – 14:00", title: "Community Lunch", type: "break", location: "Project Site" },
        ]
      },
      {
        day: "Day 2", date: "To be announced", events: [
          { time: "09:00 – 12:00", title: "Planting Session II", subtitle: "Continued planting and maintenance", type: "committee", location: "Project Site" },
          { time: "12:00 – 12:20", title: "Break", type: "break" },
          { time: "12:20 – 14:00", title: "GPS Tagging & Reporting", subtitle: "Recording and mapping every tree planted", type: "committee", location: "Project Site" },
          { time: "14:00 – 15:00", title: "Wrap-Up", subtitle: "Results shared with the community", type: "closing", location: "Regional Hub" },
        ]
      },
    ],
    // SPONSORS
    sponsorsStructureTag: "Our Structure", sponsorsStructureTitle: "Regional Teams",
    sponsorsPkgTag: "Partner With Us", sponsorsPkgTitle: "Sponsorship Packages",
    sponsorsPkgSub: "Reach 1,000+ volunteers across 14 regions and support Uzbekistan's largest grassroots reforestation effort.",
    sponsorsCtaSub: "Interested in sponsoring Yashil Qo'llar?",
    sponsorsCtaBtn: "Get in Touch",
    // TEAM
    teamSecTag: "The Leadership", teamSecTitle: "Our Team",
    teamDeptTitle: "Support Departments",
    // HOMEPAGE — quote & "what we do" (additive, used by the new HomePage design)
    quote: "Yashil Qo'llar — towards a sustainable future! Our goal is to grow ecological culture among young people. We already have 1,000+ active volunteers!",
    quoteAuthor: "Yashil Qo'llar Team",
    whatLabel: "What We Do",
    whatTitle: "Let's unite for nature.",
    whatBody: "A project to raise ecological awareness and culture among young people and protect the environment — promoting the wise use of resources, reducing waste, and strengthening ecological responsibility.",
    regionsLabel: "Project Goals",
    regions: [
      "Growing eco-knowledge", "Supporting eco-education", "Developing civic engagement",
      "Shaping ecological behavior", "Raising youth activity", "Saving resources",
      "Spreading ecological information",
    ],
    footer: {
      desc: "The ecological home for Uzbekistan's youth.",
      col1Title: "Sections",
      links1: ["Team", "Sponsors", "Blog", "Contact"],
      col2Title: "Yashil Qo'llar",
      links2: ["Mission", "Sponsors", "Contact"],
      copyright: "Yashil Qo'llar",
    },
    // LOGIN / REGISTER PAGE
    loginTag: "Yashil Qo'llar",
    loginWelcome: "Welcome back",
    loginSub: "Sign in to track your volunteer activity and projects.",
    registerTitle: "Create your account",
    registerSub: "Join without needing Telegram — sign up with just your email.",
    signIn: "Sign in", signUp: "Sign up",
    fieldFullName: "Full name", fieldEmail: "Email address", fieldPassword: "Password",
    pwPlaceholderRegister: "At least 8 characters",
    btnSignIn: "Sign in", btnCreateAccount: "Create account", btnPleaseWait: "Please wait…",
    orDivider: "or",
    continueGoogle: "Continue with Google",
    continueTelegram: "Already used our bot? Continue with Telegram",
    tgWaiting: "Waiting for confirmation in Telegram…",
    tgExpired: "Link expired — tap the button to try again.",
    noAccount: "Don't have an account?", haveAccount: "Already have an account?",
    // MAP — where we are
    mapLabel: "Where We Are",
    mapTitle: "Active across all of Uzbekistan.",
    mapBody: "Our 1,000+ volunteers are already active in every region of the country — from Karakalpakstan in the west to the Fergana Valley in the east.",
    mapRegions: [
      "Tashkent City", "Tashkent Region", "Andijan", "Fergana", "Namangan",
      "Syrdarya", "Jizzakh", "Samarkand", "Bukhara", "Navoiy",
      "Kashkadarya", "Surkhandarya", "Khorezm", "Karakalpakstan",
    ],
  },

  ru: {
    navHome: "Главная", navAbout: "О нас", navCommittees: "Проекты", navTeam: "Команда",
    navSchedule: "Мероприятия", navRegister: "Присоединиться", navSponsors: "Партнёры", navContact: "Контакты",
    dateTag: "Экологический проект",
    heroLine1: "Yashil", heroLine2: "Qo'llar", heroLine3: "объединимся", heroLine4: "ради", heroLine5: "природы.",
    heroSub: "Проект по повышению экологической осознанности и культуры среди молодёжи и защите окружающей среды — за рациональное использование ресурсов, сокращение отходов и укрепление экологической ответственности.",
    heroCta2: "Присоединяйтесь и вы к нашему пути.",
    heroBadge: "Присоединяйтесь к движению",
    btnRegister: "Присоединиться", btnCommittees: "Смотреть, чем мы занимаемся",
    stat0val: "1 000+", stat0lbl: "Волонтёров", stat1val: "25+", stat1lbl: "Мероприятий",
    stat2val: "14", stat2lbl: "Регионов", stat3val: "6", stat3lbl: "Видов деятельности",
    councilsLabel: "Чем мы занимаемся", councilsTitle: "Виды деятельности", viewAll: "Вся деятельность",
    ctaTitle1: "Строим чистое и", ctaTitle2: "устойчивое будущее",
    ctaSub: "Наша цель — развивать экологическую культуру среди молодёжи. Присоединяйтесь к 1000+ активным волонтёрам, которые уже с нами.",
    btnContact: "Связаться с нами",
    homeCommittees: [
      { code: "01", name: "Экологические акции", topic: "Уборка территорий, сортировка отходов, посадка деревьев и саженцев; конкурсы для повышения экологической ответственности." },
      { code: "02", name: "Плоггинг-мероприятия", topic: "Сбор мусора во время бега или ходьбы — спорт с пользой для экологической активности." },
      { code: "03", name: "Цифровая экопропаганда", topic: "Экологические челленджи, тренды, видео и постеры для широкой аудитории в соцсетях." },
      { code: "04", name: "Сокращение и переработка отходов", topic: "Интерактивные занятия, на которых молодёжь учится сортировать и перерабатывать отходы." },
      { code: "05", name: "Тренинги по экобезопасности", topic: "Практические навыки экологической безопасности и рационального использования природных ресурсов." },
      { code: "06", name: "Сеть эко-клубов", topic: "Эко-клубы Yashil Qo'llar в школах и вузах, конкурсы и челленджи между клубами." },
    ],
    aboutTag: "О нас",
    aboutHero: "Восстанавливаем Узбекистан,",
    aboutHeroEm: "регион за регионом",
    aboutConferenceTag: "Организация",
    aboutWhatTitle: "Что такое Yashil Qo'llar?",
    aboutP1: "Yashil Qo'llar — общественная организация, где волонтёры участвуют в реальных экологических проектах: изучают местные экосистемы, сажают деревья и восстанавливают зелёные пояса по всему Узбекистану.",
    aboutP2: "Волонтёрство у нас развивает практические, устойчивые навыки: командную работу, заботу о земле, планирование проектов, организацию сообщества и экологическую грамотность.",
    aboutP3: "Yashil Qo'llar привносит проверенную, прозрачную модель восстановления во главе с сообществом в каждый регион Узбекистана.",
    aboutSteps: [
      { step: "01", title: "Распределение по регионам", desc: "Каждый волонтёр присоединяется к проектной команде в одном из 14 регионов Узбекистана." },
      { step: "02", title: "Оценка участка", desc: "Волонтёры изучают почву, климат и потребности сообщества перед посадкой." },
      { step: "03", title: "Посадка и восстановление", desc: "Команды вместе сажают деревья, создают зелёные пояса и ухаживают за саженцами." },
      { step: "04", title: "Отчёт о результатах", desc: "Каждое дерево отмечается по GPS, данные о выживаемости публикуются открыто." },
    ],
    aboutHomeTag: "Откуда мы начали",
    aboutHomeTitle: "Ташкент, Узбекистан",
    aboutHomeP1: "Основанная в 2025 году, Yashil Qo'llar началась с небольшой волонтёрской уборки в Ташкенте.",
    aboutHomeP2: "Сегодня организация координирует экологические проекты во всех 14 регионах страны.",
    aboutValuesTag: "Наша философия", aboutValuesTitle: "Наши ценности",
    aboutValues: [
      { icon: "🌱", title: "Сначала — первопричины", desc: "Каждый проект начинается с анализа почвы, согласия общины и долгосрочного плана ухода." },
      { icon: "🤝", title: "Под руководством общины", desc: "Местные семьи, школы и фермеры сами разрабатывают и ведут каждый проект. Мы лишь помогаем." },
      { icon: "📍", title: "С учётом местности", desc: "Каждый регион получает виды растений и стратегию полива, подходящие его климату." },
      { icon: "📊", title: "Полная прозрачность", desc: "Каждое дерево отмечено по GPS. Каждый результат — включая неудачи — публикуется." },
    ],
    aboutTimelineTag: "Наш путь", aboutTimelineTitle: "История Yashil Qo'llar",
    aboutTimeline: [
      { year: "2025", event: "Основание Yashil Qo'llar", desc: "Первая уборка и посадка деревьев прошла в Ташкенте." },
      { year: "2025", event: "Региональный охват", desc: "Волонтёрские команды сформировались в Фергане, Самарканде и Навои." },
      { year: "2025", event: "Запуск GPS-учёта", desc: "Каждое посаженное дерево стало отмечаться и отслеживаться публично." },
      { year: "2025", event: "1 000+ волонтёров", desc: "Волонтёрская сеть превысила тысячу активных участников." },
      { year: "2026", event: "Все 14 регионов", desc: "Yashil Qo'llar начала работу во всех регионах Узбекистана." },
      { year: "2026", event: "25+ проектов", desc: "Наш самый амбициозный год — более 25 активных экологических проектов." },
    ],
    aboutCtaTitle: "Стань частью истории",
    aboutCtaSub: "Присоединяйтесь к волонтёрам по всему Узбекистану, восстанавливающим леса и зелёные пояса, регион за регионом.",
    aboutCtaBtn: "Присоединиться к Yashil Qo'llar",
    committeesTitle: "Проекты",
    committeeLess: "▲ Скрыть", committeeMore: "▼ Подробнее",
    committeeSeats: "мест",
    committees: [
      { code: "ТШК", name: "Зелёный пояс Ташкента", level: "Начальный", size: "40", topic1: "Городское озеленение и восстановление зелёного пояса столицы", topic2: "Общественные питомники в жилых районах", chair: "Малика Юсупова", desc: "Волонтёры сажают и ухаживают за деревьями вдоль зелёного пояса Ташкента вместе со школами и жителями.", color: "from-blue-600 to-cyan-500" },
      { code: "ФРГ", name: "Сады Ферганы", level: "Средний", size: "35", topic1: "Общественные сады и питомники саженцев по всей долине", topic2: "Водосберегающий полив для молодых саженцев", chair: "Жасур Тошматов", desc: "Проект создаёт общественные сады и обучает местных фермеров устойчивому уходу за саженцами.", color: "from-green-700 to-emerald-500" },
      { code: "ККР", name: "Восстановление Каракалпакстана", level: "Продвинутый", size: "30", topic1: "Борьба с опустыниванием у Аральского моря", topic2: "Испытания солеустойчивых видов на освоенных землях", chair: "Нилуфар Эргашева", desc: "Один из самых сложных наших проектов — восстановление растительности на землях, пострадавших от отступления Аральского моря.", color: "from-purple-700 to-violet-500" },
      { code: "НВЙ", name: "Восстановление лесов Навои", level: "Средний", size: "20", topic1: "Масштабное восстановление лесов на освоенных засушливых землях", topic2: "Обучение нового поколения местных волонтёров", chair: "Азиз Каримов", desc: "Масштабная посадка деревьев на засушливых землях Навои в сочетании с обучением волонтёров.", color: "from-amber-700 to-yellow-500" },
    ],
    regTag: "Присоединиться к нашей работе", regTitle: "Регистрация волонтёра",
    regSuccessTitle: "Заявка получена!",
    regSuccessSub: "Спасибо за заявку. Наша команда рассмотрит её и свяжется с вами по электронной почте.",
    regSuccessBtn: "Подать ещё одну заявку",
    regFeesTitle: "Как принять участие",
    fees: [
      { type: "Волонтёр", deadline: "Открыто круглый год", price: "Бесплатно", desc: "Присоединяйтесь к региональному проекту, набор для посадки и обучение включены", badge: "Популярно", badgeColor: "bg-green-500/10 text-green-400 border-green-500/20" },
      { type: "Руководитель команды", deadline: "По заявке", price: "Бесплатно", desc: "Координируйте местную проектную команду и отчитывайтесь о прогрессе", badge: "", badgeColor: "" },
      { type: "Партнёрская организация", deadline: "По заявке", price: "Бесплатно", desc: "Приведите свою школу, компанию или сообщество", badge: "Группа", badgeColor: "bg-blue-500/10 text-blue-400 border-blue-500/20" },
    ],
    regDeadline: "Доступность:",
    regFields: { firstName: "Имя", lastName: "Фамилия", email: "Электронная почта", committee1: "1-й приоритет региона", committee2: "2-й приоритет региона", experience: "Опыт волонтёрства", motivation: "Мотивационное письмо", motivationPlaceholder: "Почему вы хотите стать волонтёром?", selectCommittee: "Выберите регион", selectExperience: "Выберите уровень опыта", expNone: "Нет опыта волонтёрства", exp12: "1–2 проекта", exp35: "3–5 проектов", exp5: "5+ проектов", submit: "Отправить заявку" },
    contactTitle: "Связаться с нами",
    contactLocation: "Местоположение",
    contactAddress: "Ташкент, Узбекистан",
    faqTag: "Быстрые ответы", faqTitle: "Часто задаваемые вопросы",
    faq: [
      { q: "Кто может стать волонтёром Yashil Qo'llar?", a: "Присоединиться может любой житель Узбекистана — студенты, специалисты, семьи. Для большинства проектов опыт не требуется." },
      { q: "Есть ли плата за волонтёрство?", a: "Нет — волонтёрство бесплатно. Набор для посадки и обучение предоставляются для каждого проекта." },
      { q: "В какой регион меня направят?", a: "Вы сами выбираете предпочитаемый регион при регистрации, а наша команда подтверждает по электронной почте." },
      { q: "Когда я получу ответ после подачи заявки?", a: "Заявки обычно рассматриваются в течение 1–2 недель." },
      { q: "Может ли моя школа или компания участвовать группой?", a: "Да! Мы приветствуем школьные и корпоративные группы — свяжитесь с нами для организации группового проекта." },
    ],
    scheduleTag: "Ближайшие мероприятия", scheduleTitle: "Календарь волонтёра",
    scheduleCtaTitle: "Готовы присоединиться?",
    scheduleCtaSub: "Найдите ближайший день посадки в своём регионе и станьте частью этого.",
    scheduleCtaBtn: "Присоединиться к Yashil Qo'llar",
    scheduleTypeLabels: { opening: "Старт", committee: "День посадки", social: "Сообщество", break: "Перерыв", closing: "Итоги" },
    scheduleDays: [
      {
        day: "День 1", date: "Дата уточняется", events: [
          { time: "09:00 – 10:00", title: "Ориентация", subtitle: "Приветствие и инструктаж по безопасности для новых волонтёров", type: "opening", location: "Региональный штаб" },
          { time: "10:00 – 13:00", title: "Посадка I", subtitle: "Посадка деревьев и работа над зелёным поясом", type: "committee", location: "Площадка проекта" },
          { time: "13:00 – 14:00", title: "Общий обед", type: "break", location: "Площадка проекта" },
        ]
      },
      {
        day: "День 2", date: "Дата уточняется", events: [
          { time: "09:00 – 12:00", title: "Посадка II", subtitle: "Продолжение посадки и уход", type: "committee", location: "Площадка проекта" },
          { time: "12:00 – 12:20", title: "Перерыв", type: "break" },
          { time: "12:20 – 14:00", title: "GPS-разметка и отчёт", subtitle: "Регистрация и картирование каждого посаженного дерева", type: "committee", location: "Площадка проекта" },
          { time: "14:00 – 15:00", title: "Итоги дня", subtitle: "Результаты представлены сообществу", type: "closing", location: "Региональный штаб" },
        ]
      },
    ],
    sponsorsStructureTag: "Наша структура", sponsorsStructureTitle: "Региональные команды",
    sponsorsPkgTag: "Партнёрство", sponsorsPkgTitle: "Спонсорские пакеты",
    sponsorsPkgSub: "Охватите 1000+ волонтёров в 14 регионах и поддержите крупнейшую низовую инициативу по восстановлению лесов в Узбекистане.",
    sponsorsCtaSub: "Заинтересованы в спонсорстве Yashil Qo'llar?",
    sponsorsCtaBtn: "Связаться с нами",
    teamSecTag: "Руководство", teamSecTitle: "Наша команда",
    teamDeptTitle: "Вспомогательные отделы",
    quote: "Yashil Qo'llar — путь к устойчивому будущему! Наша цель — развивать экологическую культуру среди молодёжи. В наших рядах уже 1000+ активных волонтёров!",
    quoteAuthor: "Команда Yashil Qo'llar",
    whatLabel: "Чем мы занимаемся",
    whatTitle: "Объединимся ради природы.",
    whatBody: "Проект по повышению экологической осознанности и культуры среди молодёжи и защите окружающей среды — за рациональное использование ресурсов, сокращение отходов и укрепление экологической ответственности.",
    regionsLabel: "Цели проекта",
    regions: [
      "Повышение экознаний", "Поддержка экообразования", "Развитие вовлечённости молодёжи",
      "Формирование экоповедения", "Рост активности молодёжи", "Экономия ресурсов",
      "Распространение экоинформации",
    ],
    footer: {
      desc: "Экологический дом для молодёжи Узбекистана.",
      col1Title: "Разделы",
      links1: ["Команда", "Партнёры", "Блог", "Контакты"],
      col2Title: "Yashil Qo'llar",
      links2: ["Миссия", "Партнёры", "Контакты"],
      copyright: "Yashil Qo'llar",
    },
    loginTag: "Yashil Qo'llar",
    loginWelcome: "С возвращением",
    loginSub: "Войдите, чтобы отслеживать свою волонтёрскую активность и проекты.",
    registerTitle: "Создайте аккаунт",
    registerSub: "Регистрируйтесь без Telegram — достаточно email.",
    signIn: "Войти", signUp: "Регистрация",
    fieldFullName: "Полное имя", fieldEmail: "Электронная почта", fieldPassword: "Пароль",
    pwPlaceholderRegister: "Минимум 8 символов",
    btnSignIn: "Войти", btnCreateAccount: "Создать аккаунт", btnPleaseWait: "Подождите…",
    orDivider: "или",
    continueGoogle: "Продолжить с Google",
    continueTelegram: "Уже пользовались нашим ботом? Войти через Telegram",
    tgWaiting: "Ожидаем подтверждения в Telegram…",
    tgExpired: "Ссылка устарела — нажмите ещё раз.",
    noAccount: "Нет аккаунта?", haveAccount: "Уже есть аккаунт?",
    mapLabel: "Где мы работаем",
    mapTitle: "Активны по всему Узбекистану.",
    mapBody: "Наши 1000+ волонтёров уже работают в каждом регионе страны — от Каракалпакстана на западе до Ферганской долины на востоке.",
    mapRegions: [
      "город Ташкент", "Ташкентская область", "Андижан", "Фергана", "Наманган",
      "Сырдарья", "Джизак", "Самарканд", "Бухара", "Навои",
      "Кашкадарья", "Сурхандарья", "Хорезм", "Каракалпакстан",
    ],
  },

  uz: {
    navHome: "Bosh sahifa", navAbout: "Biz haqimizda", navCommittees: "Loyihalar", navTeam: "Jamoa",
    navSchedule: "Tadbirlar", navRegister: "Qo'shilish", navSponsors: "Homiylar", navContact: "Aloqa",
    dateTag: "Ekologik Loyiha",
    heroLine1: "Yashil", heroLine2: "Qo'llar", heroLine3: "tabiat uchun", heroLine4: "birlashamiz!",
    heroSub: "Toza va barqaror kelajak uchun birlashamiz! Yoshlar orasida ekologik ong va madaniyatni oshirish va atrof-muhitni asrashga qaratilgan loyiha bo'lib, resurslardan oqilona foydalanish, chiqindilarni kamaytirish, ekologik mas'uliyatni kuchaytirishni maqsad qiladi.",
    heroCta2: "Siz ham bizning yo'limizga qo'shiling.",
    heroBadge: "Safimizga qo'shiling",
    btnRegister: "Qo'shilish", btnCommittees: "Nima qilamiz",
    stat0val: "1 000+", stat0lbl: "Faol ko'ngillilar", stat1val: "25+", stat1lbl: "Tadbirlar",
    stat2val: "14", stat2lbl: "Hudud", stat3val: "6", stat3lbl: "Faoliyat turi",
    councilsLabel: "Nima Qilamiz", councilsTitle: "Faoliyat Turlari", viewAll: "Barcha faoliyatlar",
    ctaTitle1: "Toza va Barqaror", ctaTitle2: "Kelajak Qurish!",
    ctaSub: "Maqsadimiz — yoshlar orasida ekologik madaniyatni rivojlantirish. Safimizdagi 1000+ faol ko'ngilliga qo'shiling.",
    btnContact: "Biz bilan bog'laning",
    homeCommittees: [
      { code: "01", name: "Ekologik Aksiyalar", topic: "Hududlarni tozalash, chiqindilarni saralash, daraxt va ko'chat ekish ishlari; ekologik mas'uliyatni oshirish uchun tanlov va musobaqalar." },
      { code: "02", name: "Plogging Tadbirlari", topic: "Yugurish yoki piyoda yurish jarayonida chiqindilarni yig'ish orqali ekologik faollikni oshirish." },
      { code: "03", name: "Raqamli Ekologik Targ'ibot", topic: "Ijtimoiy tarmoqlarda ekologik challenge va trendlar, videolar va posterlar orqali keng jamoatchilikka yetkazish." },
      { code: "04", name: "Chiqindilarni Kamaytirish va Qayta Ishlash", topic: "Interaktiv mashg'ulotlar orqali chiqindilarni ajratish va qayta ishlashni o'rganish." },
      { code: "05", name: "Ekologik Xavfsizlik Treninglari", topic: "Ekologik xavfsizlik tamoyillari va tabiiy resurslardan oqilona foydalanish bo'yicha amaliy ko'nikmalar." },
      { code: "06", name: "Eko-klub Faoliyati", topic: "Maktab va universitetlarda Yashil Qo'llar eko-klublari, klublar o'rtasida musobaqa va challenge'lar." },
    ],
    aboutTag: "Biz haqimizda",
    aboutHero: "O'zbekistonni tiklaymiz,",
    aboutHeroEm: "hudud-hudud bilan",
    aboutConferenceTag: "Tashkilot",
    aboutWhatTitle: "Yashil Qo'llar nima?",
    aboutP1: "Yashil Qo'llar — ko'ngillilar real ekologik loyihalarda ishtirok etadigan jamoat tashkiloti: mahalliy ekotizimlarni o'rganish, daraxt ekish va O'zbekiston bo'ylab yashil kamarlarni tiklash.",
    aboutP2: "Biz bilan ko'ngillilik amaliy va uzoq muddatli ko'nikmalarni rivojlantiradi: jamoaviy ish, yer bilan ishlash, loyiha rejalashtirish, jamoatchilikni tashkil etish va ekologik savodxonlik.",
    aboutP3: "Yashil Qo'llar isbotlangan, shaffof jamoat boshchiligidagi tiklanish modelini O'zbekistonning har bir hududiga olib keladi.",
    aboutSteps: [
      { step: "01", title: "Hududga biriktirish", desc: "Har bir ko'ngilli O'zbekistonning 14 hududidan biridagi loyiha jamoasiga qo'shiladi." },
      { step: "02", title: "Hudud tahlili", desc: "Ko'ngillilar ekishdan oldin tuproq, iqlim va jamoat ehtiyojlarini o'rganadi." },
      { step: "03", title: "Ekish va tiklash", desc: "Jamoalar birgalikda daraxt ekadi, yashil kamarlar quradi va ko'chatlarni parvarish qiladi." },
      { step: "04", title: "Natijalarni hisobot qilish", desc: "Har bir daraxt GPS bilan belgilanadi va omon qolish ma'lumotlari ochiq e'lon qilinadi." },
    ],
    aboutHomeTag: "Biz qayerdan boshladik",
    aboutHomeTitle: "Toshkent, O'zbekiston",
    aboutHomeP1: "2025-yilda tashkil etilgan Yashil Qo'llar Toshkentdagi kichik ko'ngillilar tozalash aksiyasidan boshlandi.",
    aboutHomeP2: "Bugun tashkilot mamlakatning barcha 14 hududida ekologik loyihalarni muvofiqlashtiradi.",
    aboutValuesTag: "Bizning falsafamiz", aboutValuesTitle: "Biz nimani himoya qilamiz",
    aboutValues: [
      { icon: "🌱", title: "Avvalo ildiz sabab", desc: "Har bir loyiha tuproq tahlili, jamoat roziligi va uzoq muddatli parvarish rejasidan boshlanadi." },
      { icon: "🤝", title: "Jamoat boshchiligida", desc: "Mahalliy oilalar, maktablar va fermerlar har bir loyihani o'zlari loyihalashtiradi va egallaydi." },
      { icon: "📍", title: "Hududga moslashgan", desc: "Har bir hudud o'z iqlimiga mos turlar va suv strategiyasini oladi." },
      { icon: "📊", title: "To'liq shaffoflik", desc: "Har bir daraxt GPS bilan belgilanadi. Muvaffaqiyatsizliklar ham yashirilmaydi." },
    ],
    aboutTimelineTag: "Bizning yo'limiz", aboutTimelineTitle: "Yashil Qo'llar tarixi",
    aboutTimeline: [
      { year: "2025", event: "Yashil Qo'llar tashkil etildi", desc: "Birinchi tozalash va ekish aksiyasi Toshkentda bo'lib o'tdi." },
      { year: "2025", event: "Mintaqaviy kengayish", desc: "Farg'ona, Samarqand va Navoiyda ko'ngillilar jamoalari tuzildi." },
      { year: "2025", event: "GPS kuzatuvi ishga tushdi", desc: "Har bir ekilgan daraxt ochiq belgilanadigan va kuzatiladigan bo'ldi." },
      { year: "2025", event: "1 000+ ko'ngilli", desc: "Ko'ngillilar tarmog'i ming nafardan oshdi." },
      { year: "2026", event: "Barcha 14 hudud", desc: "Yashil Qo'llar O'zbekistonning barcha hududlarida faoliyat yurita boshladi." },
      { year: "2026", event: "25+ loyiha", desc: "Eng ambitsiyali yilimiz — 25 dan ortiq faol ekologik loyiha." },
    ],
    aboutCtaTitle: "Tarixning bir qismi bo'l",
    aboutCtaSub: "O'zbekiston bo'ylab o'rmonlar va yashil kamarlarni hudud-hudud bilan tiklayotgan ko'ngillilarga qo'shiling.",
    aboutCtaBtn: "Yashil Qo'llarga qo'shiling",
    committeesTitle: "Loyihalar",
    committeeLess: "▲ Yig'ish", committeeMore: "▼ Ko'proq",
    committeeSeats: "o'rin",
    committees: [
      { code: "TSH", name: "Toshkent yashil kamari", level: "Boshlang'ich", size: "40", topic1: "Poytaxtda shahar daraxtzorlari va yashil kamarni tiklash", topic2: "Turar-joy hududlarida jamoat ko'chatzorlari", chair: "Malika Yusupova", desc: "Ko'ngillilar Toshkent yashil kamari bo'ylab daraxt ekadi va parvarish qiladi, maktablar va aholi bilan hamkorlikda.", color: "from-blue-600 to-cyan-500" },
      { code: "FAR", name: "Farg'ona bog'lari", level: "O'rta", size: "35", topic1: "Vodiy bo'ylab jamoat bog'lari va ko'chatzorlar", topic2: "Yosh ko'chatlar uchun suv tejamkor sug'orish", chair: "Jasur Toshmatov", desc: "Loyiha jamoat bog'larini yaratadi va mahalliy fermerlarni ko'chatlarni barqaror parvarish qilishga o'rgatadi.", color: "from-green-700 to-emerald-500" },
      { code: "QQR", name: "Qoraqalpog'iston tiklanishi", level: "Yuqori", size: "30", topic1: "Orol dengizi hududida cho'llanishga qarshi kurash", topic2: "O'zlashtirilgan yerlarda sho'rga chidamli turlarni sinash", chair: "Nilufar Ergasheva", desc: "Eng murakkab loyihalarimizdan biri — Orol dengizi qisqarishi ta'sir qilgan yerlarda o'simliklarni tiklash.", color: "from-purple-700 to-violet-500" },
      { code: "NAV", name: "Navoiy o'rmontiklash", level: "O'rta", size: "20", topic1: "Qurg'oqchil yerlarda keng ko'lamli o'rmontiklash", topic2: "Yangi avlod mahalliy ko'ngillilarini o'qitish", chair: "Aziz Karimov", desc: "Navoiyning qurg'oqchil yerlarida keng ko'lamli ekish ishlari, ko'ngillilarni o'qitish bilan birga.", color: "from-amber-700 to-yellow-500" },
    ],
    regTag: "Ishimizga qo'shiling", regTitle: "Ko'ngilli sifatida ro'yxatdan o'tish",
    regSuccessTitle: "Ariza qabul qilindi!",
    regSuccessSub: "Arizangiz uchun rahmat. Jamoamiz uni ko'rib chiqadi va elektron pochta orqali siz bilan bog'lanadi.",
    regSuccessBtn: "Yana bir ariza yuborish",
    regFeesTitle: "Qanday ishtirok etish mumkin",
    fees: [
      { type: "Ko'ngilli", deadline: "Yil davomida ochiq", price: "Bepul", desc: "Hududiy loyihaga qo'shiling, ekish to'plami va treninglar bilan", badge: "Eng mashhur", badgeColor: "bg-green-500/10 text-green-400 border-green-500/20" },
      { type: "Jamoa rahbari", deadline: "Ariza bo'yicha", price: "Bepul", desc: "Mahalliy loyiha jamoasini muvofiqlashtiring va natijalarni hisobot qiling", badge: "", badgeColor: "" },
      { type: "Hamkor tashkilot", deadline: "Ariza bo'yicha", price: "Bepul", desc: "Maktabingiz, kompaniyangiz yoki jamoangizni olib keling", badge: "Guruh", badgeColor: "bg-blue-500/10 text-blue-400 border-blue-500/20" },
    ],
    regDeadline: "Mavjudlik:",
    regFields: { firstName: "Ism", lastName: "Familiya", email: "Elektron pochta", committee1: "1-chi hudud afzalligi", committee2: "2-chi hudud afzalligi", experience: "Ko'ngillilik tajribasi", motivation: "Motivatsiya xati", motivationPlaceholder: "Nima uchun ko'ngilli bo'lishni xohlaysiz?", selectCommittee: "Hududni tanlang", selectExperience: "Tajriba darajasini tanlang", expNone: "Ko'ngillilik tajribasi yo'q", exp12: "1–2 loyiha", exp35: "3–5 loyiha", exp5: "5+ loyiha", submit: "Arizani yuborish" },
    contactTitle: "Biz bilan bog'laning",
    contactLocation: "Joylashuv",
    contactAddress: "Toshkent, O'zbekiston",
    faqTag: "Tezkor javoblar", faqTitle: "Ko'p so'raladigan savollar",
    faq: [
      { q: "Yashil Qo'llarga kim ko'ngilli bo'la oladi?", a: "O'zbekistondagi har bir kishi qo'shilishi mumkin — talabalar, mutaxassislar va oilalar. Ko'pgina loyihalar uchun tajriba talab qilinmaydi." },
      { q: "Ko'ngillilik uchun to'lov bormi?", a: "Yo'q — ko'ngillilik bepul. Har bir loyiha uchun ekish to'plami va trening beriladi." },
      { q: "Meni qaysi hududga biriktirishadi?", a: "Ro'yxatdan o'tishda o'zingiz afzal ko'rgan hududni tanlaysiz, jamoamiz uni elektron pochta orqali tasdiqlaydi." },
      { q: "Ariza yuborgandan keyin qachon javob olaman?", a: "Arizalar odatda 1–2 hafta ichida ko'rib chiqiladi." },
      { q: "Maktabim yoki kompaniyam guruh bo'lib ishtirok eta oladimi?", a: "Ha! Biz maktab va kompaniya guruhlarini qabul qilamiz — guruh loyihasini tashkil qilish uchun biz bilan bog'laning." },
    ],
    scheduleTag: "Yaqinlashib kelayotgan tadbirlar", scheduleTitle: "Ko'ngillilar taqvimi",
    scheduleCtaTitle: "Bizga qo'shilishga tayyormisiz?",
    scheduleCtaSub: "Hududingizdagi keyingi ekish kunini toping va unga qo'shiling.",
    scheduleCtaBtn: "Yashil Qo'llarga qo'shiling",
    scheduleTypeLabels: { opening: "Boshlanish", committee: "Ekish kuni", social: "Jamoat", break: "Tanaffus", closing: "Yakun" },
    scheduleDays: [
      {
        day: "1-kun", date: "Sana e'lon qilinadi", events: [
          { time: "09:00 – 10:00", title: "Oriyentatsiya", subtitle: "Yangi ko'ngillilar uchun tanishuv va xavfsizlik bo'yicha ma'lumot", type: "opening", location: "Hududiy markaz" },
          { time: "10:00 – 13:00", title: "Ekish sessiyasi I", subtitle: "Daraxt ekish va yashil kamar ishlari", type: "committee", location: "Loyiha maydoni" },
          { time: "13:00 – 14:00", title: "Umumiy tushlik", type: "break", location: "Loyiha maydoni" },
        ]
      },
      {
        day: "2-kun", date: "Sana e'lon qilinadi", events: [
          { time: "09:00 – 12:00", title: "Ekish sessiyasi II", subtitle: "Ekish va parvarishni davom ettirish", type: "committee", location: "Loyiha maydoni" },
          { time: "12:00 – 12:20", title: "Tanaffus", type: "break" },
          { time: "12:20 – 14:00", title: "GPS belgilash va hisobot", subtitle: "Ekilgan har bir daraxtni qayd etish va xaritalash", type: "committee", location: "Loyiha maydoni" },
          { time: "14:00 – 15:00", title: "Yakun", subtitle: "Natijalar jamoatchilikka taqdim etiladi", type: "closing", location: "Hududiy markaz" },
        ]
      },
    ],
    sponsorsStructureTag: "Bizning tuzilmamiz", sponsorsStructureTitle: "Hududiy jamoalar",
    sponsorsPkgTag: "Hamkorlik", sponsorsPkgTitle: "Homiylik paketlari",
    sponsorsPkgSub: "14 hududdagi 1000+ ko'ngilliga yeting va O'zbekistondagi eng yirik ekologik tashabbusni qo'llab-quvvatlang.",
    sponsorsCtaSub: "Yashil Qo'llarni homiylik qilishga qiziqasizmi?",
    sponsorsCtaBtn: "Biz bilan bog'laning",
    teamSecTag: "Rahbariyat", teamSecTitle: "Bizning jamoa",
    teamDeptTitle: "Yordamchi bo'limlar",
    quote: "Yashil Qo'llar — barqaror kelajak sari! Maqsadimiz — yoshlar orasida ekologik madaniyatni rivojlantirish. Safimizda 1000+ faol ko'ngillilar bor!",
    quoteAuthor: "Yashil Qo'llar jamoasi",
    whatLabel: "Nima Qilamiz",
    whatTitle: "Tabiat uchun birlashamiz!",
    whatBody: "Yoshlar orasida ekologik ong va madaniyatni oshirish va atrof-muhitni asrashga qaratilgan loyiha bo'lib, resurslardan oqilona foydalanish, chiqindilarni kamaytirish, ekologik mas'uliyatni kuchaytirishni maqsad qiladi.",
    regionsLabel: "Loyiha Maqsadlari",
    regions: [
      "Ekobilimlarni kuchaytirish", "Ekota'limni qo'llab-quvvatlash", "Ijtimoiy jarayonlarni rivojlantirish",
      "Ekologik xulq-atvorni shakllantirish", "Yoshlar faolligini oshirish", "Resurslarni tejash",
      "Ekologik axborotlarni ko'paytirish",
    ],
    footer: {
      desc: "O'zbekiston yoshlari uchun ekologik harakat maskani.",
      col1Title: "Bo'limlar",
      links1: ["Jamoa", "Homiylar", "Blog", "Aloqa"],
      col2Title: "Yashil Qo'llar",
      links2: ["Missiya", "Homiylar", "Aloqa"],
      copyright: "Yashil Qo'llar",
    },
    loginTag: "Yashil Qo'llar",
    loginWelcome: "Xush kelibsiz",
    loginSub: "Ko'ngillilik faoliyatingiz va loyihalaringizni kuzatish uchun kiring.",
    registerTitle: "Hisob yarating",
    registerSub: "Telegram shart emas — faqat email bilan ro'yxatdan o'ting.",
    signIn: "Kirish", signUp: "Ro'yxatdan o'tish",
    fieldFullName: "To'liq ism", fieldEmail: "Elektron pochta", fieldPassword: "Parol",
    pwPlaceholderRegister: "Kamida 8 ta belgi",
    btnSignIn: "Kirish", btnCreateAccount: "Hisob yaratish", btnPleaseWait: "Kuting…",
    orDivider: "yoki",
    continueGoogle: "Google orqali davom etish",
    continueTelegram: "Botimizdan foydalanganmisiz? Telegram orqali kiring",
    tgWaiting: "Telegramda tasdiqlashni kutmoqda…",
    tgExpired: "Havola eskirdi — qayta bosing.",
    noAccount: "Hisobingiz yo'qmi?", haveAccount: "Hisobingiz bormi?",
    mapLabel: "Qayerda Ishlaymiz",
    mapTitle: "Butun O'zbekiston bo'ylab faolmiz.",
    mapBody: "Bizning 1000+ faol ko'ngillimiz mamlakatning har bir hududida allaqachon faoliyat yuritmoqda — g'arbdagi Qoraqalpog'istondan sharqdagi Farg'ona vodiysigacha.",
    mapRegions: [
      "Toshkent shahri", "Toshkent viloyati", "Andijon", "Farg'ona", "Namangan",
      "Sirdaryo", "Jizzax", "Samarqand", "Buxoro", "Navoiy",
      "Qashqadaryo", "Surxondaryo", "Xorazm", "Qoraqalpog'iston",
    ],
  },
} as const;

export type Translations = typeof translations.en;
interface LangCtx { lang: Lang; setLang: (l: Lang) => void; t: Translations; }
const LanguageContext = createContext<LangCtx>({ lang: "en", setLang: () => { }, t: translations.en });
export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [lang, setLang] = useState<Lang>("en");
  return <LanguageContext.Provider value={{ lang, setLang, t: translations[lang] }}>{children}</LanguageContext.Provider>;
};
export const useLang = () => useContext(LanguageContext);